discord:
  token: "placeholder" #This is where your Discord bot token goes
  prefix: "!" #This is the prefix for the commands
  commands: #This is where you can edit the commands for completing actions in Discord
    claim_command: "claim"
    start_command: "start"
    stop_command: "stop"
    delete_command: "deletecharacter"
    help_command: "help"

